# Generated by Django 3.1.4 on 2021-07-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0002_auto_20210710_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(blank=True, default='Self taking', max_length=100),
        ),
    ]
