# Generated by Django 3.1.4 on 2021-07-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_auto_20210710_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
