# Generated by Django 3.1.4 on 2021-07-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0004_auto_20210710_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_mode',
            field=models.CharField(default='self taking', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='doc_cost',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='doc_type',
            field=models.CharField(default='pdf', max_length=255),
            preserve_default=False,
        ),
    ]
