# Generated by Django 3.1.4 on 2021-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0005_auto_20210713_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='printing', max_length=255),
            preserve_default=False,
        ),
    ]
