# Generated by Django 3.1.4 on 2021-07-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0006_booking_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
