# Generated by Django 3.1.4 on 2021-07-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0007_location_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='stationery',
            field=models.ForeignKey(default='HQ', on_delete=django.db.models.deletion.CASCADE, to='stationery.stationery'),
            preserve_default=False,
        ),
    ]
