# Generated by Django 3.1.4 on 2021-07-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0009_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
