# Generated by Django 3.1.4 on 2021-07-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0010_booking_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
