# Generated by Django 3.1.4 on 2021-07-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0011_auto_20210725_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='stock',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stationery.product'),
        ),
    ]
