# Generated by Django 3.1.4 on 2021-07-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0012_auto_20210727_0244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
