# Generated by Django 3.1.4 on 2021-08-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.service'),
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
