# Generated by Django 3.1.4 on 2021-08-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0016_auto_20210801_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='stationery',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('', 'Office-Supply'), ('Folders', 'Folders'), ('Tapes', 'Tapes'), ('Ink', 'Ink'), ('Craft', 'Craft'), ('Market', 'Market'), ('Clips', 'Clips'), ('Artist-Corner', 'Artist-Corner'), ('Paper', 'Paper'), ('Pencils', 'Pencils'), ('Colours', 'Colours'), ('Pens', 'Pens'), ('Books', 'Books'), ('Acts', 'Acts'), ('Refills', 'Refills'), ('Cases', 'Cases'), ('ID`s', 'ID`s')], max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, choices=[('', 'printing'), ('scanning', 'scanning'), ('emailing', 'emailing')], max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='task_type',
            field=models.CharField(blank=True, choices=[('', 'individual'), ('group', 'group'), ('report', 'report'), ('research', 'research'), ('paper', 'paper')], max_length=150, null=None),
        ),
    ]
