# Generated by Django 3.1.4 on 2021-08-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0017_auto_20210801_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('printing', 'printing'), ('scanning', 'scanning'), ('emailing', 'emailing')], max_length=100),
        ),
    ]
