# Generated by Django 3.1.4 on 2021-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0018_auto_20210801_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_mode',
            field=models.CharField(choices=[('', 'self taking'), ('Nakutunuku', 'Nakutunuku'), ('LT1', 'LT1'), ('Library', 'Library')], default='Nakutunuku', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('printing', 'printing'), ('scanning', 'scanning'), ('emailing', 'emailing')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
