# Generated by Django 3.1.4 on 2021-08-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0019_auto_20210801_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_mode',
            field=models.CharField(choices=[('self taking', 'self taking'), ('Nakutunuku', 'Nakutunuku'), ('LT1', 'LT1'), ('Library', 'Library')], default='self taking', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Office-Supply', 'Office-Supply'), ('Folders', 'Folders'), ('Tapes', 'Tapes'), ('Ink', 'Ink'), ('Craft', 'Craft'), ('Market', 'Market'), ('Clips', 'Clips'), ('Artist-Corner', 'Artist-Corner'), ('Paper', 'Paper'), ('Pencils', 'Pencils'), ('Colours', 'Colours'), ('Pens', 'Pens'), ('Books', 'Books'), ('Acts', 'Acts'), ('Refills', 'Refills'), ('Cases', 'Cases'), ('ID`s', 'ID`s')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
