# Generated by Django 3.1.4 on 2021-08-03 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0020_auto_20210802_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 3, 2, 36, 39, 888764, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'pending'), ('received', 'received'), ('complete', 'complete')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
