# Generated by Django 3.1.4 on 2021-08-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0021_auto_20210802_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approve',
        ),
        migrations.AddField(
            model_name='stationery',
            name='approve_ID',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
