# Generated by Django 3.1.4 on 2021-08-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0025_auto_20210803_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStationery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stationery.stationery',),
        ),
    ]
