# Generated by Django 3.1.4 on 2021-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0026_pendingstationery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='approve_ID',
            field=models.BooleanField(default=False),
        ),
    ]
