# Generated by Django 3.1.4 on 2021-08-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0027_auto_20210804_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationery',
            old_name='approve_ID',
            new_name='status',
        ),
    ]
