# Generated by Django 3.1.4 on 2021-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0030_remove_stationery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationery',
            name='approval01',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='stationery',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
