# Generated by Django 3.1.4 on 2021-08-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0032_auto_20210804_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationery',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
