# Generated by Django 3.1.4 on 2021-08-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0033_auto_20210804_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationery',
            options={'verbose_name_plural': 'Stationeries'},
        ),
    ]
